### ISSUE TITLE
When you start rendering, it has 3 secs of still frame then starts counting.

### ISSUE THREAD

**Issue by knock2one** [KaleidonKep99/KeppyNotesCounter#1]
You should add a box to take away the 3 second still frame (if the people choose too, like me)

**Comment by KaleidonKep99** [comment]
Will do.

**Comment by KaleidonKep99** [comment]
Added as of [version 1.0.2](https://github.com/KaleidonKep99/KeppyCounterGenerator/releases/tag/1.0.2).
