### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by AG89** [KaleidonKep99/KeppyNotesCounter#2]
Can't render output codec as QT Animation or else the file doesn't show up at all after rendering

**Comment by KaleidonKep99** [comment]
It's my fault, I made a typo in the code... Will fix it soon.

**Comment by KaleidonKep99** [comment]
Fixed as of [version 1.0.2](https://github.com/KaleidonKep99/KeppyCounterGenerator/releases/tag/1.0.2).
