### ISSUE TITLE
Midi too big to convert?

### ISSUE THREAD

**Issue by AG89** [KaleidonKep99/KeppyNotesCounter#3]
I tried converting a 500 million note midi and this happened
![2017-11-09_20-33-30](https://user-images.githubusercontent.com/22873716/32638498-9102eb76-c58d-11e7-9ccd-9228aeea1645.png)

**Comment by KaleidonKep99** [comment]
Fixed.
https://github.com/KaleidonKep99/KeppyCounterGenerator/releases/tag/1.0.5
